title:              CESTES
email:              cestes@idiv.de
description:        'A global database for metaCommunity Ecology:<br>Species, Traits, Environment and Space'
author:             Alienor Jeliazkov
baseurl:            "" # "/startbootstrap-clean-blog-jekyll"
url:                "https://icestes.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    iCESTES
# facebook_username:  StartBootstrap
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
